---
- block:
    - name: Install terminal applications
      pacman:
        name:
          - btop
          - nvtop
          - fastfetch
          - nano
          - neovim
        state: present

    - name: Install utilities applications
      pacman:
        name:
          - gnome-calculator
          - gnome-connections
          - gnome-calendar
          - gnome-disk-utility
          - baobab
          - gnome-system-monitor
          - gedit
          - snapshot
          - simple-scan
          - evince
          - file-roller
        state: present
      when: application.utilities == true
    
    - name: Install development applications
      pacman:
        name:
          - dbeaver
        state: present
      when: application.development == true

    - name: Install Code - OSS
      pacman:
        name:
          - code
        state: present
      when: aur.enable != true and application.development == true

    - name: Install graphical applications
      pacman:
        name:
          - gimp
          - inkscape
        state: present
      when: application.graphical == true
    
    - name: Install audio applications
      pacman:
        name:
          - audacity
        state: present
      when: application.audio == true
    
    - name: Install video applications
      pacman:
        name:
          - kdenlive
          - obs-studio
        state: present
      when: application.video == true
    
    - name: Install 3D applications
      pacman:
        name:
          - blender
          - freecad
        state: present
      when: application.three_dimensional == true
  become: true
