---
- block:
    - name: Install terminal applications
      pacman:
        name:
          - btop
          - nvtop
          - cmatrix
          - fastfetch
          - nano
          - neovim
        state: present

    - name: Install graphical applications
      pacman:
        name:
          - kalk
          - gimp
          - inkscape
          - blender
          - freecad
        state: present

    - name: Install Code - OSS
      pacman:
        name:
          - code
        state: present
      when: aur.enable != true
  become: true
