---
- block:
    - name: Create AUR directory
      file:
        path: "{{ aur.directory }}"
        owner: "{{ lookup(''env'', ''USER'') }}"
        group: "{{ lookup(''env'', ''USER'') }}"
        state: directory

    - name: Install AUR base packages
      aur:
        name: "{{ aur.packages }}"
        user: "{{ lookup(''env'', ''USER'') }}"

    - name: Install AUR google-chrome
      aur:
        name: google-chrome
        user: "{{ lookup(''env'', ''USER'') }}"
      when: browser == google-chrome
  become: true
