---
- block:
    - name: Create AUR directory
      file:
        path: "{{ aur.directory }}"
        state: directory
  become: false

- block:
    - name: Install AUR base packages
      aur:
        dir: "{{ aur.directory }}"
        name: "{{ aur.packages }}"
        user: "{{ lookup('env', 'USER') }}"

    - name: Install AUR google-chrome
      aur:
        dir: "{{ aur.directory }}"
        name: google-chrome
        user: "{{ lookup('env', 'USER') }}"
      when: browser == 'google-chrome'
  become: true
