---
- block:
    - name: Create AUR directory
      file:
        path: "{{ aur.directory }}"
        state: directory
  become: false

- block:
    - name: Install AUR base packages
      aur:
        dir: "{{ aur.directory }}"
        name: "{{ aur.packages }}"
        user: "{{ lookup('env', 'USER') }}"

    - name: Install AUR google-chrome
      aur:
        dir: "{{ aur.directory }}"
        name: google-chrome
        user: "{{ lookup('env', 'USER') }}"
      when: browser == 'google-chrome'

    - name: Install AUR onlyoffice-bin
      aur:
        dir: "{{ aur.directory }}"
        name: onlyoffice-bin
        user: "{{ lookup('env', 'USER') }}"
      when: application.utilities == true

    - name: Install AUR visual-studio-code-bin
      aur:
        dir: "{{ aur.directory }}"
        name: visual-studio-code-bin
        user: "{{ lookup('env', 'USER') }}"
      when: application.development == true
  become: true
