---
- block:
    - name: Install browser firefox
      pacman:
        name:
          - firefox
        state: present
      when: browser == 'firefox'

    - name: Install browser chromium
      pacman:
        name:
          - chromium
        state: present
      when: browser == 'chromium'

    - name: Install browser vivaldi
      pacman:
        name:
          - vivaldi
        state: present
      when: browser == 'vivaldi'

    - name: Install AUR google-chrome
      command: yay -S --noconfirm google-chrome
      when: browser == 'google-chrome'
      become_user: "{{ lookup('env', 'USER') }}"
      when: aur.enable == true and browser == 'google-chrome'
  become: true
