---
- block:
    - name: Install general packages
      pacman:
        name:
          - curl
          - wget
        state: present

    - name: Install archive packages
      pacman:
        name:
          - p7zip
          - unrar
          - unzip
          - xz
          - zip
          - bzip2
          - gzip
          - tar
        state: present

    - name: Install multimedia packages
      pacman:
        name:
          - mesa
          - vulkan-tools
          - vulkan-intel
          - networkmanager
          - bluez
          - pipewire
          - pipewire-pulse
          - qt6-multimedia-ffmpeg
        state: present

    - name: Install development packages
      pacman:
        name:
          - base-devel
          - git
          - python
          - cargo
          - nodejs
          - npm
        state: present
  become: true

- block:
    - name: Enable and start the service NetworkManager
      systemd:
        name: NetworkManager
        enabled: true
        state: started

    - name: Enable and start the service bluetooth
      systemd:
        name: bluetooth
        enabled: true
        state: started
  become: true
