---
- block:
  - name: Install login manager
    pacman:
      name:
        - greetd
        - greetd-regreet
      state: present

  - name: Enable and start the service greetd
    systemd:
      name: greetd
      enabled: true
      state: started
  become: true