- name: Install login manager
  pacman:
    name:
      - greetd
      - greetd-regreet
    state: present

###################################################
# TODO: Enable services
###################################################
# sudo systemctl enable greetd
# sudo systemctl start greetd