---
- block:
    - name: Clone dotfiles from repository
      git:
        repo: "{{ dotfiles.url }}"
        dest: /tmp/dotfiles
        update: true
  become: false

- block:
    - name: Remove existing ~/.config/
      file:
        path: "{{ lookup('env', 'HOME') }}/.config/"
        state: absent
      when: dotfiles.clear_before == true

    - name: Copy dotfiles to ~/
      copy:
        src: /tmp/dotfiles/
        dest: "{{ lookup('env', 'HOME') }}"
        remote_src: true

    - name: Remove ~/.git
      file:
        path: "{{ lookup('env', 'HOME') }}/.git"
        state: absent
  become: false

- block:
    - name: Remove existing /root/.config/oh-my-posh/
      file:
        path: /root/.config/oh-my-posh/
        state: absent

    - name: Copy oh-my-posh configuration to root
      copy:
        src: /tmp/dotfiles/.config/oh-my-posh/
        dest: /root/.config/oh-my-posh/
        remote_src: true
  become: true
