---
- block:
    - name: Install Hyprland dependencies
      pacman:
        name:
          - polkit
          - egl-wayland
          - alsa-utils
          - pamixer
          - playerctl
          - brightnessctl
          - libnotify
          - qt5ct
          - qt6ct
          - qt5-wayland
          - qt6-wayland
          - xdg-desktop-portal-wlr
          - dunst
          - gnome-themes-extra
        state: present

    - name: Install Hyprland and utilities
      pacman:
        name:
          - hyprland
          - hyprpicker
          - waybar
          - rofi
          - swww
          - swayidle
          - hyprlock
          - nwg-bar
          - network-manager-applet
          - bluez-utils
          - blueman
          - alacritty
          - jq
          - nautilus
          - ark
          - imv
          - wl-clipboard
          - grim
          - slurp
          - sox
        state: present
  become: true

- block:
    - name: Copy greetd configuration files
      copy:
        src: common/files/etc/greetd/
        dest: /etc/greetd/
        remote_src: true

    - name: Update greetd config.toml to set the user
      lineinfile:
        path: /etc/greetd/config.toml
        regexp: "^user = "
        line: 'user = "{{ lookup(''env'', ''USER'') }}"'
  become: true

- block:
    - name: Find Linux entries
      find:
        paths: /boot/loader/entries/
        patterns: "*linux*.conf"
      register: linux_entries

    - name: Update boot entry for quiet mode
      lineinfile:
        path: "{{ item.path }}"
        regexp: "^(options.*)$"
        line: \1 quiet loglevel=3 rd.systemd.show_status=auto rd.udev.log_priority=3
        backrefs: true
      loop: "{{ linux_entries.files }}"
  become: true
  
- block:
    - name: Set chromium to use wayland
      replace:
        path: /usr/share/applications/chromium.desktop
        regexp: "^(Exec=.*)$"
        replace: \1 --enable-features=UseOzonePlatform --ozone-platform=wayland
      when: browser == 'chromium'

    - name: Set google-chrome to use wayland
      replace:
        path: /usr/share/applications/google-chrome.desktop
        regexp: "^(Exec=.*)$"
        replace: \1 --enable-features=UseOzonePlatform --ozone-platform=wayland
      when: browser == 'google-chrome'
  become: true

- block:
    - name: Removing window buttons in Gnome
      shell: gsettings set org.gnome.desktop.wm.preferences button-layout ":"
  become: false
