- name: Print username
  ansible.builtin.debug:
    msg: "Username: {{ username }}"

- name: check updates
  pacman: 
   update_cache: yes
   upgrade: yes

- include_tasks: core.yml

- include_tasks: nvidia.yml

- include_tasks: fonts.yml

- include_tasks: applications.yml

- include_tasks: display-manager.yml

- include_tasks: hyprland.yml

- include_tasks: dotfiles.yml