---
- block:
    - name: Update package cache
      pacman:
        update_cache: yes

    - name: Upgrade all installed packages
      pacman:
        upgrade: yes
  become: true

- include_tasks: dotfiles.yml

- include_tasks: core.yml

- include_tasks: nvidia.yml

- include_tasks: fonts.yml

- include_tasks: applications.yml

- include_tasks: display-manager.yml

- include_tasks: hyprland.yml
