---
- block:
    - name: Install Nvidia drivers
      pacman:
        name:
          - nvidia
          - nvidia-utils
          - lib32-nvidia-utils
          - nvidia-prime
          - nvidia-settings
          - nvtop
        state: present
  become: true

- block:
    - name: Edit mkinitcpio.conf to add Nvidia modules
      replace:
        path: /etc/mkinitcpio.conf
        regexp: '^(MODULES=\()([^)]*)(\))'
        replace: 'MODULES=(\2 nvidia nvidia_modeset nvidia_uvm nvidia_drm)'

    - name: Create modprobe configuration for Nvidia DRM
      copy:
        dest: /etc/modprobe.d/nvidia.conf
        content: |
          options nvidia_drm modeset=1 fbdev=1

    - name: Regenerate initramfs
      command: mkinitcpio -P
  become: true
