[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]
# command = "Hyprland -c /etc/greetd/hyprland.conf > /dev/null 2>&1"
command = "Hyprland > /dev/null 2>&1"
user = "your_user"
